server:
  port: 8092

spring:
  application:
    name: index

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2